// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	model "github.com/MarselBissengaliyev/advertising/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockAdvert is a mock of Advert interface.
type MockAdvert struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertMockRecorder
}

// MockAdvertMockRecorder is the mock recorder for MockAdvert.
type MockAdvertMockRecorder struct {
	mock *MockAdvert
}

// NewMockAdvert creates a new mock instance.
func NewMockAdvert(ctrl *gomock.Controller) *MockAdvert {
	mock := &MockAdvert{ctrl: ctrl}
	mock.recorder = &MockAdvertMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvert) EXPECT() *MockAdvertMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdvert) Create(advert model.CreateAdvertsBody) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", advert)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdvertMockRecorder) Create(advert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdvert)(nil).Create), advert)
}

// GetAll mocks base method.
func (m *MockAdvert) GetAll(limit, page int, orderBy string) ([]model.GetAllAdvertsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", limit, page, orderBy)
	ret0, _ := ret[0].([]model.GetAllAdvertsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAdvertMockRecorder) GetAll(limit, page, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAdvert)(nil).GetAll), limit, page, orderBy)
}

// GetById mocks base method.
func (m *MockAdvert) GetById(advertId int, fields []string) (model.Advert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", advertId, fields)
	ret0, _ := ret[0].(model.Advert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAdvertMockRecorder) GetById(advertId, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAdvert)(nil).GetById), advertId, fields)
}
